//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaStankBankUploader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ytUser {
            get {
                return ((string)(this["ytUser"]));
            }
            set {
                this["ytUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ytPass {
            get {
                return ((string)(this["ytPass"]));
            }
            set {
                this["ytPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wpUser {
            get {
                return ((string)(this["wpUser"]));
            }
            set {
                this["wpUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wpPass {
            get {
                return ((string)(this["wpPass"]));
            }
            set {
                this["wpPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstTime {
            get {
                return ((bool)(this["firstTime"]));
            }
            set {
                this["firstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string outputpath {
            get {
                return ((string)(this["outputpath"]));
            }
            set {
                this["outputpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bgimage {
            get {
                return ((string)(this["bgimage"]));
            }
            set {
                this["bgimage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.theootz.com/dastankbank/")]
        public string wpURL {
            get {
                return ((string)(this["wpURL"]));
            }
            set {
                this["wpURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Da Stank Bank\r\nMusic Blog For Drum & Bass, Dubstep, Electro\r\n\r\nYoutube:\r\nhttp://w" +
            "ww.youtube.com/user/Dastankbank\r\nBlog:\r\nhttp://www.theootz.com/dastankbank/\r\nFac" +
            "ebook:\r\nhttp://www.facebook.com/pages/Toronto-ON/Da-Stank-Bank/257926353411?ref=" +
            "ts")]
        public string ytDesc {
            get {
                return ((string)(this["ytDesc"]));
            }
            set {
                this["ytDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"%albumart%
<object classid=""clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"" width=""480"" height=""295"" codebase=""http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0""><param name=""allowFullScreen"" value=""true"" /><param name=""allowscriptaccess"" value=""always"" /><param name=""src"" value=""http://www.youtube.com/v/%YTID%&hl=en_US&fs=1&rel=0&color1=0x3873bd&color2=0x3873bd"" /><param name=""allowfullscreen"" value=""true"" /><embed type=""application/x-shockwave-flash"" width=""480"" height=""295"" src=""http://www.youtube.com/v/%YTID%&hl=en_US&fs=1&rel=0&color1=0x3873bd&color2=0x3873bd"" allowscriptaccess=""always"" allowfullscreen=""true""></embed></object>")]
        public string wpPost {
            get {
                return ((string)(this["wpPost"]));
            }
            set {
                this["wpPost"] = value;
            }
        }
    }
}
